[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/countries"
  to = "https://restcountries.com/v3.1/all?fields=name,cca2"
  status = 200
  force = true

[[redirects]]
  from = "/api/ipinfo"
  to = "https://ipwho.is/"
  status = 200
  force = true

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
